### ISSUE TITLE
bug回報&希望能加回舊版能夠以其他條件排列歌曲的功能

### ISSUE THREAD

**Issue by KiyuM1n** [Dogeon188/chuni-tools#1]
舊版能夠以overpower等等的其他條件來排列 希望能加回這個功能
![image](https://user-images.githubusercontent.com/68652201/218984324-3603d597-7a78-4504-9d58-53e30ad9f26c.png)

在使用新版的時候rating為0.00的歌曲的排名會有錯亂的情況
![image](https://user-images.githubusercontent.com/68652201/218984744-96518921-c473-4177-b30b-46718d302feb.png)
在舊版是沒有這個bug的
![image](https://user-images.githubusercontent.com/68652201/218984849-db5ea994-d914-4dcb-a263-1dc2d01c8752.png)

**Comment by Dogeon188** [comment]
首先是關於排序的問題

排序的功能一直是有的，我只是把他從設定裡面移除掉，變成只能從th調整。
會這樣做主要還是因為我加了反向排序的功能，我個人認為如果再加個調整反向排序的按鈕會讓設定畫面變得過於擁擠，所以就把他拿掉了。當然了，也有一部分是因為這樣做起來比較方便，節省程式碼。
如果你是不知道他還在的話，想知道什麼樣的方式能夠更明顯的表達「可以透過table head排序」這件事，畢竟這就是accessibility的問題。如果你是希望他加回設定頁面的話，如上述，短期之內應該不會加回來。我是有預計要把比較detail的設定分開，變成類似net原本那種可以開關advanced settings的作法，可能到時候才會再考慮。

再來關於你提到的bug，應該是因為我把「未遊玩樂曲」列入排名的原因。
做這個是為了over power的顯示，因為我自己不會遇到這種狀況就沒發現了(´･ω･`)
稍早修好並push了，希望你可以幫我測試一下，感恩～

**Comment by KiyuM1n** [comment]
感謝作者的回覆以及說明

目前經過了測試 問題已經修復完成了

最後想問的是
與舊版最大的差別是
新版是會需要額外跳轉到查分器的網頁
舊版則是直接在原本的chunithm-net作顯示
想請問為什麼會有這個更動呢？
(並不是有所不滿 只是想瞭解這麼做的用意)

再次感謝作者～

**Comment by Dogeon188** [comment]
原本的作法會牽涉到shadowRoot的操作，我個人覺得…不太好。所以索性把他揚了
另外也是因為我拿來~~抄~~參考的maimai查分器是這樣寫，考慮過後我也覺得這樣不錯，能夠把抓取跟顯示分開來。
以前沒有分開來，導致debug的時候反而相對麻煩，也經常遇到使用者說查分器無法執行（雖然現在也是，我也沒什麼好解方），目前這樣應該是比較好掌控的。
